name: Build Kernel for rosemary

on:
  workflow_dispatch:

jobs:
  build:
    name: Kernel Compilation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3
      with:
        repository: piwkiddd/kernel_xiaomi_rosemary
        path: kernel
        ref: main  # Optional: set to a specific branch or tag if needed

    - name: Clone aarch64 Toolchain
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
        path: aarch64

    - name: Clone arm Toolchain
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
        path: arm

    - name: Clone Clang Toolchain
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
        path: clang

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make libc6-dev \
        libncurses5-dev libncursesw5-dev xz-utils curl lzop git gcc g++

    - name: Compile Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CLANG_PATH=$GITHUB_WORKSPACE/clang/bin
        export CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64/bin/aarch64-linux-android-
        export CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm/bin/arm-linux-androideabi-
        export PATH=$CLANG_PATH:$PATH

        cd kernel

        # Replace with actual defconfig if different
        make O=out rosemary_defconfig

        make -j$(nproc) O=out \
          CC=clang \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi-

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v3
      with:
        name: Image.gz-dtb-${{ github.ref_name }}
        path: kernel/out/arch/arm64/boot/Image.gz-dtb
