name: Build Kernel for rosemary

on:
  workflow_dispatch:

jobs:
  build:
    name: Kernel Compilation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3
      with:
        repository: piwkiddd/kernel_xiaomi_rosemary
        path: kernel

    - name: Clone aarch64 Toolchain
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
        path: aarch64

    - name: Clone arm Toolchain
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
        path: arm

    - name: Clone Clang Toolchain
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
        path: clang
