name: Build Kernel Rosemary (Clang)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: piwkiddd/kernel_xiaomi_rosemary
          path: kernel
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            build-essential \
            libssl-dev \
            libncurses-dev \
            flex \
            bison \
            libelf-dev \
            curl \
            device-tree-compiler \
            git \
            python3 \
            python3-pip \
            unzip \
            wget \
            ccache \
            clang \
            lld \
            llvm \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi

      - name: Set Kernel Config
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          make O=out rosemary_defconfig

      - name: Build Kernel with Clang
        run: |
          cd kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_HOST=github
          export KBUILD_BUILD_USER=piwkiddd
          export PATH=/usr/lib/llvm-18/bin:$PATH

          make -j$(nproc) O=out \
            CC=clang \
            LD=ld.lld \
            NM=llvm-nm \
            AR=llvm-ar \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            LLVM=1 \
            LLVM_IAS=1

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: Image.gz-dtb
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
