name: Build Kernel for rosemary

on:
  workflow_dispatch:

jobs:
  build:
    name: Kernel Compilation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        repository: piwkiddd/kernel_xiaomi_rosemary
        path: kernel
        ref: R  # Ganti dengan branch atau tag yang sesuai

    - name: Clone GCC Toolchains (aarch64 & arm)
      run: |
        git clone --depth=1 https://github.com/arter97/aarch64-linux-android-4.9.git aarch64
        git clone --depth=1 https://github.com/arter97/arm-linux-androideabi-4.9.git arm

    - name: Clone Clang Toolchain (r487747c)
      uses: actions/checkout@v4
      with:
        repository: LineageOS/android_prebuilts_clang_host_linux-x86_clang-r487747c
        path: clang

    - name: Install Build Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make libc6-dev \
        libncurses5-dev libncursesw5-dev xz-utils curl lzop git gcc g++ build-essential

    - name: Compile Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CLANG_PATH=$GITHUB_WORKSPACE/clang/bin
        export CROSS_COMPILE=$GITHUB_WORKSPACE/aarch64/bin/aarch64-linux-android-
        export CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/arm/bin/arm-linux-androideabi-
        export PATH=$CLANG_PATH:$PATH

        cd kernel

        # Ganti dengan defconfig lain jika diperlukan
        make O=out rosemary_defconfig

        make -j$(nproc) O=out \
          CC=clang \
          LD=ld.lld \
          AR=llvm-ar \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip \
          CROSS_COMPILE=aarch64-linux-android- \
          CROSS_COMPILE_ARM32=arm-linux-androideabi-

    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz-dtb-${{ github.ref_name }}
        path: kernel/out/arch/arm64/boot/Image.gz-dtb
